import { Event} from "./event";

export const EVENTS: Event[] = [
  { id: 1, name: 'pirmas', checkpointCount: 10, checkpoints: [{ id: "1", latitude: 10, longtitude: 11, name: "geras"}], teams: [{ id: "pirma", name: "teamas", members: [{id: "pir", firstName: "vardas", lastName: "pavarde", password: "pass"}]}], teamSize: 4, created: "2011-01-01", starting: "asdasdasd", status: "Closed", estimatedTime: 10564, estimatedDistance: 999, description: "asdasdasd" },
  { id: 2, name: 'antras', checkpointCount: 11, checkpoints: [{ id: "1", latitude: 10, longtitude: 11, name: "geras"}], teams: [{ id: "pirma", name: "teamas", members: [{id: "pir", firstName: "vardas", lastName: "pavarde", password: "pass"}]}], teamSize: 5, created: "2010-01-01", starting: "asdasdasd", status: "Closed", estimatedTime: 10564, estimatedDistance: 999, description: "asdasdasd" },
  { id: 3, name: 'trecias', checkpointCount: 5, checkpoints: [{ id: "1", latitude: 10, longtitude: 11, name: "geras"}], teams: [{ id: "pirma", name: "teamas", members: [{id: "pir", firstName: "vardas", lastName: "pavarde", password: "pass"}]}], teamSize: 2, created: "2015-01-01", starting: "asdasdasd", status: "Closed", estimatedTime: 10564, estimatedDistance: 999, description: "asdasdasd" },
  { id: 4, name: 'ketvirtas', checkpointCount: 6, checkpoints: [{ id: "1", latitude: 10, longtitude: 11, name: "geras"}], teams: [{ id: "pirma", name: "teamas", members: [{id: "pir", firstName: "vardas", lastName: "pavarde", password: "pass"}]}], teamSize: 8, created: "2003-01-01", starting: "asdasdasd", status: "Closed", estimatedTime: 10564, estimatedDistance: 999, description: "asdasdasd" },
  { id: 5, name: 'penktas', checkpointCount: 8, checkpoints: [{ id: "1", latitude: 10, longtitude: 11, name: "geras"}], teams: [{ id: "pirma", name: "teamas", members: [{id: "pir", firstName: "vardas", lastName: "pavarde", password: "pass"}]}], teamSize: 3, created: "2019-01-01", starting: "asdasdasd", status: "Closed", estimatedTime: 10564, estimatedDistance: 999, description: "asdasdasd" },
  { id: 11, name: 'pirmas', checkpointCount: 10, checkpoints: [{ id: "1", latitude: 10, longtitude: 11, name: "geras"}], teams: [{ id: "pirma", name: "teamas", members: [{id: "pir", firstName: "vardas", lastName: "pavarde", password: "pass"}]}], teamSize: 4, created: "2011-01-01", starting: "asdasdasd", status: "Open", estimatedTime: 10564, estimatedDistance: 999, description: "asdasdasd" },
  { id: 2, name: 'antras', checkpointCount: 11, checkpoints: [{ id: "1", latitude: 10, longtitude: 11, name: "geras"}], teams: [{ id: "pirma", name: "teamas", members: [{id: "pir", firstName: "vardas", lastName: "pavarde", password: "pass"}]}], teamSize: 5, created: "2010-01-01", starting: "asdasdasd", status: "Closed", estimatedTime: 10564, estimatedDistance: 999, description: "asdasdasd" },
  { id: 13, name: 'trecias', checkpointCount: 5, checkpoints: [{ id: "1", latitude: 10, longtitude: 11, name: "geras"}], teams: [{ id: "pirma", name: "teamas", members: [{id: "pir", firstName: "vardas", lastName: "pavarde", password: "pass"}]}], teamSize: 2, created: "2015-01-01", starting: "asdasdasd", status: "Closed", estimatedTime: 10564, estimatedDistance: 999, description: "asdasdasd" },
  { id: 42, name: 'ketvirtas', checkpointCount: 6, checkpoints: [{ id: "1", latitude: 10, longtitude: 11, name: "geras"}], teams: [{ id: "pirma", name: "teamas", members: [{id: "pir", firstName: "vardas", lastName: "pavarde", password: "pass"}]}], teamSize: 8, created: "2003-01-01", starting: "asdasdasd", status: "Closed", estimatedTime: 10564, estimatedDistance: 999, description: "asdasdasd" },
  { id: 53, name: 'penktas', checkpointCount: 8, checkpoints: [{ id: "1", latitude: 10, longtitude: 11, name: "geras"}], teams: [{ id: "pirma", name: "teamas", members: [{id: "pir", firstName: "vardas", lastName: "pavarde", password: "pass"}]}], teamSize: 3, created: "2019-01-01", starting: "asdasdasd", status: "Closed", estimatedTime: 10564, estimatedDistance: 999, description: "asdasdasd" },
  { id: 14, name: 'pirmas', checkpointCount: 10, checkpoints: [{ id: "1", latitude: 10, longtitude: 11, name: "geras"}], teams: [{ id: "pirma", name: "teamas", members: [{id: "pir", firstName: "vardas", lastName: "pavarde", password: "pass"}]}], teamSize: 4, created: "2011-01-01", starting: "asdasdasd", status: "Closed", estimatedTime: 10564, estimatedDistance: 999, description: "asdasdasd" },
  { id: 25, name: 'antras', checkpointCount: 11, checkpoints: [{ id: "1", latitude: 10, longtitude: 11, name: "geras"}], teams: [{ id: "pirma", name: "teamas", members: [{id: "pir", firstName: "vardas", lastName: "pavarde", password: "pass"}]}], teamSize: 5, created: "2010-01-01", starting: "asdasdasd", status: "Closed", estimatedTime: 10564, estimatedDistance: 999, description: "asdasdasd" },
  { id: 36, name: 'trecias', checkpointCount: 5, checkpoints: [{ id: "1", latitude: 10, longtitude: 11, name: "geras"}], teams: [{ id: "pirma", name: "teamas", members: [{id: "pir", firstName: "vardas", lastName: "pavarde", password: "pass"}]}], teamSize: 2, created: "2015-01-01", starting: "asdasdasd", status: "Closed", estimatedTime: 10564, estimatedDistance: 999, description: "asdasdasd" },
  { id: 47, name: 'ketvirtas', checkpointCount: 6, checkpoints: [{ id: "1", latitude: 10, longtitude: 11, name: "geras"}], teams: [{ id: "pirma", name: "teamas", members: [{id: "pir", firstName: "vardas", lastName: "pavarde", password: "pass"}]}], teamSize: 8, created: "2003-01-01", starting: "asdasdasd", status: "Closed", estimatedTime: 10564, estimatedDistance: 999, description: "asdasdasd" },
  { id: 58, name: 'penktas', checkpointCount: 8, checkpoints: [{ id: "1", latitude: 10, longtitude: 11, name: "geras"}], teams: [{ id: "pirma", name: "teamas", members: [{id: "pir", firstName: "vardas", lastName: "pavarde", password: "pass"}]}], teamSize: 3, created: "2019-01-01", starting: "asdasdasd", status: "Closed", estimatedTime: 10564, estimatedDistance: 999, description: "asdasdasd" },
  { id: 15, name: 'pirmas', checkpointCount: 10, checkpoints: [{ id: "1", latitude: 10, longtitude: 11, name: "geras"}], teams: [{ id: "pirma", name: "teamas", members: [{id: "pir", firstName: "vardas", lastName: "pavarde", password: "pass"}]}], teamSize: 4, created: "2011-01-01", starting: "asdasdasd", status: "Closed", estimatedTime: 10564, estimatedDistance: 999, description: "asdasdasd" },
  { id: 22, name: 'antras', checkpointCount: 11, checkpoints: [{ id: "1", latitude: 10, longtitude: 11, name: "geras"}], teams: [{ id: "pirma", name: "teamas", members: [{id: "pir", firstName: "vardas", lastName: "pavarde", password: "pass"}]}], teamSize: 5, created: "2010-01-01", starting: "asdasdasd", status: "Closed", estimatedTime: 10564, estimatedDistance: 999, description: "asdasdasd" },
  { id: 32, name: 'trecias', checkpointCount: 5, checkpoints: [{ id: "1", latitude: 10, longtitude: 11, name: "geras"}], teams: [{ id: "pirma", name: "teamas", members: [{id: "pir", firstName: "vardas", lastName: "pavarde", password: "pass"}]}], teamSize: 2, created: "2015-01-01", starting: "asdasdasd", status: "Closed", estimatedTime: 10564, estimatedDistance: 999, description: "asdasdasd" },
  { id: 44, name: 'ketvirtas', checkpointCount: 6, checkpoints: [{ id: "1", latitude: 10, longtitude: 11, name: "geras"}], teams: [{ id: "pirma", name: "teamas", members: [{id: "pir", firstName: "vardas", lastName: "pavarde", password: "pass"}]}], teamSize: 8, created: "2003-01-01", starting: "asdasdasd", status: "Closed", estimatedTime: 10564, estimatedDistance: 999, description: "asdasdasd" },
  { id: 58, name: 'penktas', checkpointCount: 8, checkpoints: [{ id: "1", latitude: 10, longtitude: 11, name: "geras"}], teams: [{ id: "pirma", name: "teamas", members: [{id: "pir", firstName: "vardas", lastName: "pavarde", password: "pass"}]}], teamSize: 3, created: "2019-01-01", starting: "asdasdasd", status: "Closed", estimatedTime: 10564, estimatedDistance: 999, description: "asdasdasd" },
  { id: 15, name: 'pirmas', checkpointCount: 10, checkpoints: [{ id: "1", latitude: 10, longtitude: 11, name: "geras"}], teams: [{ id: "pirma", name: "teamas", members: [{id: "pir", firstName: "vardas", lastName: "pavarde", password: "pass"}]}], teamSize: 4, created: "2011-01-01", starting: "asdasdasd", status: "Closed", estimatedTime: 10564, estimatedDistance: 999, description: "asdasdasd" },
  { id: 15, name: 'antras', checkpointCount: 11, checkpoints: [{ id: "1", latitude: 10, longtitude: 11, name: "geras"}], teams: [{ id: "pirma", name: "teamas", members: [{id: "pir", firstName: "vardas", lastName: "pavarde", password: "pass"}]}], teamSize: 5, created: "2010-01-01", starting: "asdasdasd", status: "Closed", estimatedTime: 10564, estimatedDistance: 999, description: "asdasdasd" },
  { id: 16, name: 'trecias', checkpointCount: 5, checkpoints: [{ id: "1", latitude: 10, longtitude: 11, name: "geras"}], teams: [{ id: "pirma", name: "teamas", members: [{id: "pir", firstName: "vardas", lastName: "pavarde", password: "pass"}]}], teamSize: 2, created: "2015-01-01", starting: "asdasdasd", status: "Closed", estimatedTime: 10564, estimatedDistance: 999, description: "asdasdasd" },
  { id: 18, name: 'ketvirtas', checkpointCount: 6, checkpoints: [{ id: "1", latitude: 10, longtitude: 11, name: "geras"}], teams: [{ id: "pirma", name: "teamas", members: [{id: "pir", firstName: "vardas", lastName: "pavarde", password: "pass"}]}], teamSize: 8, created: "2003-01-01", starting: "asdasdasd", status: "Closed", estimatedTime: 10564, estimatedDistance: 999, description: "asdasdasd" },
  { id: 51, name: 'penktas', checkpointCount: 8, checkpoints: [{ id: "1", latitude: 10, longtitude: 11, name: "geras"}], teams: [{ id: "pirma", name: "teamas", members: [{id: "pir", firstName: "vardas", lastName: "pavarde", password: "pass"}]}], teamSize: 3, created: "2019-01-01", starting: "asdasdasd", status: "Closed", estimatedTime: 10564, estimatedDistance: 999, description: "asdasdasd" }
];
